services:
  ice-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ice-frontend
    ports:
      - "4000:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    restart: unless-stopped